### ISSUE TITLE
Type mismatch: inferred type is String? but String was expected

### ISSUE THREAD

**Issue by khaledkhj** [keval-devani/custom_social_share#14]
![image](https://github.com/keval-devani/custom_social_share/assets/142454381/a3c18139-c0b1-474e-8256-e1ac5abd2605)

Running on specs:
Flutter 3.19.6 • channel stable
Tools • Dart 3.3.4 • DevTools 2.31.1

**Comment by hbassole** [comment]
> ![image](https://private-user-images.githubusercontent.com/142454381/329818111-a3c18139-c0b1-474e-8256-e1ac5abd2605.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MTM4MDcsIm5iZiI6MTcxNTYxMzUwNywicGF0aCI6Ii8xNDI0NTQzODEvMzI5ODE4MTExLWEzYzE4MTM5LWMwYjEtNDc0ZS04MjU2LWUxYWM1YWJkMjYwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxNTE4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDA2MjVjOTkyNWU4NTk5ZjE4MzdlMDgwMWIzOWZlMDFiYzAyODZhZWVlYWMwNWQ2M2M0ZDJmNjc1MDExMzdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sUE9tF8R-4YsFK_MHRwMERfnnWTYW8MXmAApJFEhw9g)
> 
> Running on specs: Flutter 3.19.6 • channel stable Tools • Dart 3.3.4 • DevTools 2.31.1

Hi,
use this in your yml file to fix 
````
custom_social_share:
    git:
      url: https://github.com/keval-devani/custom_social_share.git
      ref: cd25c83f5ca468c92a2cd13526fddb555049e4b0
````
